// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGame;

import java.util.ArrayList;

// TODO: Auto-generated Javadoc
/**
 * The Class ChoiceD stores the current list of alive demons
 */
public class ChoiceD {

	/** The elementd array stores exhaustive list all the demons */
	private Element[] elementd = new Element[6];

	/**
	 * The l demon. array list stores current list of demons used in an encounter
	 */
	private ArrayList<Element> l_demon = new ArrayList<Element>();

	/**
	 * Gets the l demon
	 *
	 * @return the l demon
	 */
	public ArrayList<Element> getL_demon() {
		return l_demon;
	}

	/** The l demon history faint. */
	private ArrayList<Element> l_demon_history_faint = new ArrayList<Element>();

	/**
	 * Gets the l demon history faint.
	 *
	 * @return the l demon history faint
	 */
	public ArrayList<Element> getL_demon_history_faint() {
		return l_demon_history_faint;
	}

	/**
	 * Sets the l demon history faint.
	 *
	 * @param l_demon_history_faint the new l demon history faint
	 */
	public void setL_demon_history_faint(ArrayList<Element> l_demon_history_faint) {
		this.l_demon_history_faint = l_demon_history_faint;
	}

	/**
	 * Sets the l demon.
	 *
	 * @param l_demon the new l demon
	 */
	public void setL_demon(ArrayList<Element> l_demon) {
		this.l_demon = l_demon;
	}

	/** The l demon check. */
	ArrayList<Element> l_demon_check = new ArrayList<Element>();

	/**
	 * Gets the element.
	 *
	 * @return the element
	 */
	public Element[] getElement() {
		return elementd;
	}

	/**
	 * Instantiates a new choice D. use random number generator to pick 3 different/
	 * unique list of demons from array of elementd
	 */
	public ChoiceD() {
		elementd[0] = new Element("spider", 10, 20, "N.A");
		elementd[1] = new Element("mummy", 80, 50,"N.A");
		elementd[2] = new Element("slime", 30, 20,"N.A");
		elementd[3] = new Element("manticore", 80, 100,"N.A");
		elementd[4] = new Element("gremlin", 50, 100,"N.A");
		elementd[5] = new Element("aishwarya", 60, 100,"N.A");
		int[] mat = new int[3];
		for (int i = 0; i < 3; i++) {
			mat[i] = (int) (Math.random() * elementd.length);
			if (i > 0)
				for (int c = 0; c <= i - 1; c++)
					if (mat[c] == mat[i])
						i--;
		}
		/*
		 * for (int i=0;i<mat.length;i++) //generate non repetitive random numbers {
		 * System.out.println(mat[i]); }
		 */
		/*
		 * for (int i=0;i<l_demon.length;i++) { l_demon[i]=elementd[i]; }
		 */
		/*
		 * System.out.println("Choose your demons (3):"); int [] mat=new int[3]; Scanner
		 * ch = new Scanner(System.in); for (int i=0;i<3;i++) { mat[i]=ch.nextInt(); }
		 */
		for (int i = 0; i < 3; i++) {
			l_demon.add(elementd[mat[i]]);
		}

		// ch.close();
	}

	/**
	 * Gets the new demons. gets a fresh list of demons when the user clears a round
	 * Moreover, the demons becomes stronger this time since, there health points
	 * and attack/ strength are increased by 10 points
	 */
	public void get_new_demons() {
		int[] mat = new int[3];
		for (int i = 0; i < 3; i++) {
			mat[i] = (int) (Math.random() * elementd.length);
			if (i > 0)
				for (int c = 0; c <= i - 1; c++)
					if (mat[c] == mat[i])
						i--;
		}
		for (int i = 0; i < 3; i++) {
			l_demon.add(elementd[mat[i]]);
		}
		for (int j = 0; j < l_demon.size(); j++) {
			l_demon.get(j).setMaxhp(l_demon.get(j).getMaxhp() + 10);
			l_demon.get(j).setHp(l_demon.get(j).getMaxhp());
			l_demon.get(j).setAttack(l_demon.get(j).getAttack() + 10);
		}

		// ch.close();
	}

}
