// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGame;

// TODO: Auto-generated Javadoc
/**
 * *********************************************************.
 */
/**
 * 
 */
public class Element {

	/** The name : Describes the name of the warrior/ demon */
	private String name;

	/**
	 * Gets the name.
	 * 
	 * @return the name of warrior/ demon
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the name of the warrior/ demon
	 *
	 * @param name the new
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the attack/ Strength of warrior/ demon
	 *
	 * @return the attack point
	 */
	public int getAttack() {
		return attack;
	}

	/**
	 * Sets the attack.
	 *
	 * @param attack the new attack
	 */
	public void setAttack(int attack) {
		this.attack = attack;
	}

	/**
	 * Gets the (hp) current health point of the warrior/ demon
	 *
	 * @return the hp
	 */
	public int getHp() {
		return hp;
	}

	/**
	 * Sets the (hp) current health point to any value passed as the argument
	 *
	 * @param hp the new hp
	 */
	public void setHp(int hp) {
		this.hp = hp;
	}

	/**
	 * Checks if is faint.
	 *
	 * @return true, if warrior/ demon faint is true
	 */
	public boolean isFaint() {
		return faint;
	}

	/**
	 * Sets the faint boolean value to true/false
	 *
	 * @param faint the new faint
	 */
	public void setFaint(boolean faint) {
		this.faint = faint;
	}

	/**
	 * The attack/ Strength of the warrior/ demon Type : Integer
	 **/
	private int attack;

	/**
	 * The hp. Current health points
	 **/
	private int hp;

	/**
	 * The maxhp. Maximum health points possible
	 **/
	private int maxhp;

	/**
	 * Gets the maxhp.
	 *
	 * @return the maxhp
	 */
	public int getMaxhp() {
		return maxhp;
	}

	/**
	 * Sets the maxhp.
	 *
	 * @param maxhp the new maxhp
	 */
	public void setMaxhp(int maxhp) {
		this.maxhp = maxhp;
	}

	/** The faint. */
	private boolean faint;
	
	/** The desciption. */
	private String desciption;

	/**
	 * Gets the desciption.
	 *
	 * @return the desciption
	 */
	public String getDesciption() {
		return desciption;
	}

	/**
	 * Sets the desciption.
	 *
	 * @param desciption the new desciption
	 */
	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	/**
	 * Instantiates a new element.
	 *
	 * @param name the name of warrior/ demon
	 * @param atk  the attack / Strength
	 * @param hp   the hp
	 */
	public Element(String name, int atk, int hp, String description) {
		this.name = name;
		this.attack = atk;
		this.maxhp = hp;
		this.hp = hp;
		this.desciption=description;
	}

	/**
	 * F 1. A function used to attack the opponent Basically to reduce the health
	 * point of opponents
	 * 
	 * @param b the b
	 */
	public void f1(int b) {
		this.hp -= b;
		if (this.hp <= 0) {
			this.hp = 0;
			this.faint = true;
			System.out.println("the " + this.name + " has fainted......");
		}

	}

};
