// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGame;

import java.util.Scanner;

/************************************************************/
/**
 * @author Vishal Vishal
 * @author Aishwarya Singh Rathore
 * @version 5.0 
 * \n Describes the overall structure of the game
 */
public class Game {

	// public static Encounter encounter=new Encounter();

	public static GUI gui;

	/**
	 * The main method.
	 *
	 * @param args the arguments
	 * 
	 */
	public static void main(String[] args) {

		int quit = 1;
		Scanner sc = new Scanner(System.in);
		GUI gui = new GUI();
		/**
		 * creates an instance of GUI: Game Interface
		 */
		// gui.print();
		int g = gui.E.p;
		int input_level;
		/*
		 * System.out.println("\nDo you want to skip to level (2 or 3):");
		 * input_level=sc.nextInt(); if (input_level==2) { gui.E.level_flag=true; }
		 */
		do {
			// gui.display();
			// encounter.play();
			if (gui.E.choiced.getL_demon().isEmpty() == true || gui.E.level_flag == true) {
				System.out.println("\n\n\n\nWelcome to level " + ++gui.E.p + "\tDemons are stronger this time");
				// gui = new GUI();
				gui.E.choiced.getL_demon().clear();
				gui.E.regain(gui.E.choicew);
				gui.E.choiced.get_new_demons();
				// gui.print();
				gui.E.level_flag = false;
			}
			gui.print();
			gui.E.attackD();
			gui.print();
			gui.E.attackW();
			gui.print();

			for (int i = 0; i < gui.E.choicew.getL_warrior_history_faint().size(); i++) {
				System.out.println(gui.E.choicew.getL_warrior_history_faint().get(i).getName());
			}
			if (gui.E.checkw() == true) {
				System.out.println("All the heroes are dead. You loose.... ");
				break;
			}
			while (true) {
				System.out.println("Do you want to quit(true/false) - press(1/0): ");
				quit = sc.nextInt();
				if (quit == 1 || quit == 0)
					break;
			}
		} while (quit == 0 || gui.E.p == 4);
		// sc.close();
		System.out.println("\nThank you for playing MAE Game!! à bientôt!!");
	}
	/**
	 * 
	 */
};
