// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAEGame;

/**
 * *********************************************************
 * Graphical user
 * interface of the Game
 */
public class GUI {

	// public Encounter E=new Encounter();
	public Encounter E;

	/**
	 * Instantiates a new gui. Graphical user Interface Creates an instance of
	 * encounter required at each level of the game
	 */
	public GUI() {
		System.out.println("Welcome to MAE Game gui");
		E = new Encounter();
	}

	/**
	 * Prints the the current status of demons and warriors currently playing the
	 * game
	 */
	public void print() {

		ChoiceD demon = E.choiced;
		ChoiceW warrior = E.choicew;
		System.out.println("------------------------------------------------------");
		System.out.println("\t Demons");
		for (int i = 0; i < demon.getL_demon().size(); i++)
			System.out.println("D " + (i + 1) + ":" + demon.getL_demon().get(i).getName() + "\t Strength="
					+ demon.getL_demon().get(i).getAttack() + "\t HP=" + demon.getL_demon().get(i).getHp() + "/"
					+ demon.getL_demon().get(i).getMaxhp());
		System.out.println("------------------------------------------------------");
		System.out.println("\t Warriors");
		for (int i = 0; i < warrior.getL_warrior().size(); i++)
			System.out.println("W " + (i + 1) + ":" + warrior.getL_warrior().get(i).getName() + "\t Strength="
					+ warrior.getL_warrior().get(i).getAttack() + " \t HP=" + warrior.getL_warrior().get(i).getHp()
					+ "/" + warrior.getL_warrior().get(i).getMaxhp());
		System.out.println("------------------------------------------------------");
	}

};
